"""
Configuration package.
"""

from .constants import (
    ALLOWED_EXTENSIONS,
    DEFAULT_PAGE_SIZE,
    MAX_OPTION_LENGTH,
    MAX_PAGE_SIZE,
    MAX_QUESTION_LENGTH,
    MAX_RATING,
    MAX_TEMPLATE_LENGTH,
    MAX_UPLOAD_SIZE,
    MAX_VERSION_HISTORY,
    MIN_RATING,
    TABLE_CONTEXTS,
    TABLE_FEEDBACK,
    TABLE_INSTRUCTIONS,
    TABLE_ITERATIONS,
    TABLE_QUESTIONS,
    TABLE_VARIANTS,
    TABLE_VERSIONS,
)
from .settings import Settings, get_settings, settings

__all__ = [
    "Settings",
    "get_settings",
    "settings",
    "TABLE_QUESTIONS",
    "TABLE_CONTEXTS",
    "TABLE_INSTRUCTIONS",
    "TABLE_VERSIONS",
    "TABLE_VARIANTS",
    "TABLE_FEEDBACK",
    "TABLE_ITERATIONS",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "MAX_UPLOAD_SIZE",
    "ALLOWED_EXTENSIONS",
    "MAX_QUESTION_LENGTH",
    "MAX_OPTION_LENGTH",
    "MAX_TEMPLATE_LENGTH",
    "MAX_VERSION_HISTORY",
    "MIN_RATING",
    "MAX_RATING",
]
